Controllers films users
vladrassvet/java-filmorate pull request #4
Opened 2023-10-06 10:11 UTC by vladrassvet

Initial pull request

2023-10-06 21:27 UTC, Frilock requested changes
Добрый вечер, довольно много комментариев к работе

2023-10-06 21:27 UTC, Frilock commented on pom.xml
> +			<version>1.18.30</version>
Версии библиотек, которые вы подключаете в pom файле, правильнее писать в preporties (по аналогии с версией java), поскольку pom файлы могут быть очень большого размера и изменение версии библиотеки может оказаться не такой простой задачей.

2023-10-06 21:27 UTC, Frilock commented on pom.xml
> +
Лишние пустые строки

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +
Лишняя пустая строка

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private HashMap<Integer, Film> list = new HashMap<>();
В сигнатуре метода стараемся указывать интерфейс, а не реализацию

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
static final поля по code style пишут в таком формате - LOG ( или LOGGER)

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> get() {
метод логичнее назвать getAll

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (validateName(film) && validateDuration(film) && validateDescription(film) && validateReleaseDate(film)) {
Чтобы избавится от лишней вложенности инвертируйте условие

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +                throw new ValidationException("Фильм не найден в базе данных");
Какой фильм? Хотя бы в логе и исключении id/code указывайте

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        Film newFilm = new Film();
А зачем создавать до if? Если все равно только при одном условии заполняете обьект

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            if (film.getName().length() == 0) {
Инвертируйте условие, чтобы отказаться от лишней вложенности

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getDescription().length() > 200) {
А если description null? Используйте проверку StringUtils.isNotBlank
от apacheCommon 3

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.parse("1895-12-28"))) {
а если дата null?

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +
Лишняя пустая строка

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public HashMap<Integer, Film> getHashMap() {
А зачем вообще этот метод? и что за странное название

2023-10-06 21:27 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        filmController = new FilmController();
Зачем создавать обьекты перед каждым тестом? А что если их 20 будет ?

2023-10-06 21:27 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    private FilmController filmController;
Лучше разделить на 2 тестовых класса

2023-10-06 21:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController {
Комментарии в данном контроллере аналогичны предыдущему

2023-10-07 12:32 UTC, vladrassvet commented on pom.xml
> +
Исправлено

2023-10-07 12:32 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +
Исправлено

2023-10-07 12:32 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private HashMap<Integer, Film> list = new HashMap<>();
Исправлено

2023-10-07 12:32 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
Исправлено

2023-10-07 12:33 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +
Исправлено

2023-10-07 12:35 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public HashMap<Integer, Film> getHashMap() {
Этот метод используется тестами для получения списка всех значений в базе для их сверки. Переименовал его в returnList.

2023-10-07 12:37 UTC, vladrassvet commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        filmController = new FilmController();
Предлагаете исправить init на @BeforeAll?

2023-10-08 12:24 UTC, vladrassvet commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    private FilmController filmController;
Исправлено

2023-10-08 12:24 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController {
Исправлено

2023-10-08 13:32 UTC, vladrassvet commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +        filmController = new FilmController();
Я так сделал по аналогии с 7м заданием, где также инициализировал объекты для работы перед каждым тестом и проблем тогда не возникло. Пожалуйста, не считайте это за ошибку, это часть необходимой логики, чтобы не удлинять каждый тест инициализацией переменных.

2023-10-08 13:35 UTC, vladrassvet commented on pom.xml
> +			<version>1.18.30</version>
Исправлено

2023-10-08 15:57 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> get() {
Исправлено

2023-10-08 16:25 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        Film newFilm = new Film();
Это необходимо для return в конце метода. Я пробовал переносить переменную в if, но там return его не видит, поэтому приходиться инициализировать его заранее. Хотя можно объявить его, но создать новый объект в if. Особой разницы я тут не вижу.

2023-10-09 08:25 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            if (film.getName().length() == 0) {
Исправлено

2023-10-09 08:25 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        Film newFilm = new Film();
Исправлено

2023-10-09 08:27 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getDescription().length() > 200) {
Не смог найти проверку StringUtils.isNotBlank, просто сделал проверку на значение null

2023-10-09 08:32 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.parse("1895-12-28"))) {
Исправлено

2023-10-09 08:34 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +                throw new ValidationException("Фильм не найден в базе данных");
Исправлено

2023-10-09 08:35 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (validateName(film) && validateDuration(film) && validateDescription(film) && validateReleaseDate(film)) {
Не совсем понимаю как и зачем это надо сделать. Вроде бы логика в коде правильная, что значение должно пройти все проверки на валидацию и только потом обрабатываться.

2023-10-09 17:38 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getDescription().length() > 200) {
А где вы искали? Библиотеку надо подключить https://mvnrepository.com/artifact/org.apache.commons/commons-lang3

2023-10-09 17:43 UTC, Frilock requested changes
Добрый вечер, еще ряд комментариев

2023-10-09 17:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private static final Logger LOG = LoggerFactory.getLogger(FilmController.class);
Можно аннотацию от lombok использовать slf4j

2023-10-09 17:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return toReturn;
3 строчки можно обьдинить в 1

2023-10-09 17:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +
Лишняя пустая строка

2023-10-09 17:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User post(@RequestBody User user) {
Название метода путает, дайте нормальное

2023-10-09 17:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            else
Обособьте скобками if и else, поможет избегать ошибок по невнимательности

2023-10-09 17:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User put(@RequestBody User user) {
Аналогично

2023-10-09 17:43 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public boolean validateBirthday(User user) {
По хорошему методы валидации лучше вынести в отдельный класс

2023-10-09 18:32 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User post(@RequestBody User user) {
Исправлено

2023-10-10 07:20 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return toReturn;
Исправлено

2023-10-10 07:20 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private static final Logger LOG = LoggerFactory.getLogger(FilmController.class);
Исправлено

2023-10-10 07:21 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +
Исправлено

2023-10-10 07:21 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            else
Исправлено

2023-10-10 07:21 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User put(@RequestBody User user) {
Исправлено

2023-10-10 07:23 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public boolean validateBirthday(User user) {
Тогда надо будет создавать отдельный класс валидации для Film и для User. Мне кажется логичнее всё же делать валидацию в классе, который отвечает за обработку данных и добавления новых значений в базу. Хотя, конечно, можно заморочиться и на отдельные классы.

2023-10-10 16:23 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public boolean validateBirthday(User user) {
Отдельные классы правильнее, поскольку каждый класс отвечает за какую то конкретную задачу. У вас класс контроллера принимает запросы (в дальнейшем будет проксировать запросы в сервис), а валидация это уже отдельная функциональность

2023-10-10 16:23 UTC, Frilock approved these changes
Принято, на вопрос ответил

2023-10-10 16:41 UTC, merged