Add SQL database (Task 11)
vladrassvet/java-filmorate pull request #6
Opened 2023-11-17 10:29 UTC by vladrassvet

2023-11-18 09:36 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев

2023-11-18 09:36 UTC, Frilock commented on pom.xml
> +
Лишний пропуск

2023-11-18 09:36 UTC, Frilock commented on pom.xml
> +            <version>1.7.0</version>
Версию вынесите в пропертис

2023-11-18 09:36 UTC, Frilock commented on pom.xml
> +            <groupId>org.apache.maven.plugins</groupId>
А эту зависимость лучше в plugins

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreMpaController.java
> +    GenreMpaService genreMpaService;
Приватный модификатор

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Используйте StringUtils.isNotBlank/isBlank, в данной библиотеке (apache common 3) довольно много полезных методов

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> -@AllArgsConstructor
А почему ломбок перестали использовать?

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +    public Film(int id, String name, String description, LocalDate releaseDate, int duration, MPA mpa) {
Зачем вам столько конструкторов? Это в последствии может создавать проблемы

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/GenreMpaService.java
> +@Slf4j
Лишняя аннотация

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    private final UserDbStorage userDbStorage;
Инжектите интерфейс, а не реализацию, с тем или иным Qualifaer

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +
лишняя пустая строка

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                resultSet.getDate("release_data").toLocalDate(),
а дата null не может быть?

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreMpaDbStorage.java
> +
Лишняя пустая строка

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreMpaDbStorage.java
> +    public MPA rowMpa(ResultSet rs, int i) throws SQLException {
А почему методы публичные? их же нет в интерфейсе

2023-11-18 09:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public List<User> getFriendOfFriends(int id, int oderId) {
Метод точно публичный должен быть?

2023-11-18 09:36 UTC, Frilock commented on src/main/resources/schema.sql
> +--DROP TABLE friends,likes,users, genre, film_genre, MPA, films;
Уберите, раз не нужно

2023-11-18 09:36 UTC, Frilock commented on src/main/resources/schema.sql
> +	login varchar(20) NOT NULL,
Используйте в скриптах форматирование одного вида, тут оно у вас сьезжает

2023-11-18 09:36 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/services/FilmServiceTest.java
> +    FilmStorage filmStorage;
Модификаторы

2023-11-18 09:36 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/services/UserServiceTest.java
> +    User user;
Модификаторы

2023-11-18 10:25 UTC, vladrassvet commented on pom.xml
> +
Выполнено

2023-11-18 10:28 UTC, vladrassvet commented on pom.xml
> +            <version>1.7.0</version>
Я следовал стилю написания кода на https://mvnrepository.com/ где версия указывается в том же блоке, что и остальной код, что мне кажется логичным. Если это не так и лучше версии выносить в пропертис, пожалуйста, скажите какой блок нужно там правильно назвать для этого.

2023-11-18 10:28 UTC, vladrassvet commented on pom.xml
> +            <groupId>org.apache.maven.plugins</groupId>
Выполнено

2023-11-18 10:29 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreMpaController.java
> +    GenreMpaService genreMpaService;
Выполнено

2023-11-18 10:31 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) {
Выполнено

2023-11-18 10:33 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public List<User> getFriendOfFriends(int id, int oderId) {
Исправлено на private

2023-11-18 10:34 UTC, vladrassvet commented on src/main/resources/schema.sql
> +--DROP TABLE friends,likes,users, genre, film_genre, MPA, films;
Как раз для автономных тестов постмана надо очистить все таблицы, поэтому решил оставить в виде комментария. Пожалуйста, не считайте это за ошибку или излишний код, так как это функциональный комментарий SQL.

2023-11-18 10:37 UTC, vladrassvet commented on src/main/resources/schema.sql
> +	login varchar(20) NOT NULL,
![user](https://github.com/vladrassvet/java-filmorate/assets/134495843/6a244e58-68f8-4a17-a0eb-3f56d993d7ce)
Странно, у меня в IDEA всё отображается нормально, иначе я бы заметил и выровнял бы. На всякий случай вставил везде tab.

2023-11-18 10:38 UTC, vladrassvet commented on src/test/java/ru/yandex/practicum/filmorate/services/FilmServiceTest.java
> +    FilmStorage filmStorage;
Исправлено

2023-11-18 10:38 UTC, vladrassvet commented on src/test/java/ru/yandex/practicum/filmorate/services/UserServiceTest.java
> +    User user;
Исправлено

2023-11-18 10:44 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public List<User> getFriendOfFriends(int id, int oderId) {
Всё же он должен быть публичным, иначе не проходит тест в pull request:
 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project filmorate: Compilation failure
Error:  /home/runner/work/java-filmorate/java-filmorate/src/main/java/ru/yandex/practicum/filmorate/services/UserService.java:[49,29] getFriendOfFriends(int,int) has private access in ru.yandex.practicum.filmorate.storage.UserDbStorage

2023-11-18 10:57 UTC, vladrassvet commented on pom.xml
> +            <version>1.7.0</version>
Ещё хотел сказать, что это версия файла, которую мне скинул наставник Артём Дяченко после того, как я написал в общем чате о проблемах с плагинами и зависимостями. У него именно так написано.

2023-11-19 09:56 UTC, Frilock commented on src/main/resources/schema.sql
> +--DROP TABLE friends,likes,users, genre, film_genre, MPA, films;
Хорошо

2023-11-19 09:59 UTC, Frilock commented on pom.xml
> +            <version>1.7.0</version>
Не очень понял ваш вопрос про блок.  Есть специальный блок properties, где указываются номера версий библиотек. На mvnreporitory так указано для простоты, чтобы вам было удобнее зависимость подключать, но если представить что в вашем пом файле пару сотен, а может и тысяч зависимостей, скролить код будет не очень приятно. Кроме того, так будет проще отслеживать изменения версий через git blame - кто, когда, по какой задаче

2023-11-19 10:00 UTC, Frilock requested changes
Добрый день, на часть комментариев мне не ответили. Вообще те комментарии которые вы поправили можно "закрывать"

2023-11-19 10:29 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreMpaDbStorage.java
> +    public MPA rowMpa(ResultSet rs, int i) throws SQLException {
Исправлено

2023-11-19 10:29 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreMpaDbStorage.java
> +
Исправлено

2023-11-19 10:34 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    private final UserDbStorage userDbStorage;
Не совсем понял как это лучше сделать. Пожалуйста, подскажите что именно вы ожидаете увидеть. Вроде бы по смыслу всё подходит правильно.

2023-11-19 10:35 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> -@AllArgsConstructor
Исправлено

2023-11-19 10:36 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +    public Film(int id, String name, String description, LocalDate releaseDate, int duration, MPA mpa) {
Исправлено

2023-11-19 10:36 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/services/GenreMpaService.java
> +@Slf4j
Исправлено

2023-11-19 10:37 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +
Исправлено

2023-11-19 10:39 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                resultSet.getDate("release_data").toLocalDate(),
Нет, дата проходит валидацию при добавлении фильма, там у меня уже стоит проверка на null.

2023-11-19 10:45 UTC, vladrassvet commented on pom.xml
> +            <version>1.7.0</version>
Я имел ввиду, что не знаю как вынести версию в properties. Пожалуйста, подскажите как это должно быть оформлено.

2023-11-19 14:45 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    private final UserDbStorage userDbStorage;
Или вы имеете ввиду перенести все методы упоминаемые в UserDbStorage в интерфейс UserStorage?

2023-11-20 18:32 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    private final UserDbStorage userDbStorage;
Те которые используются в других классах должны быть в интерфейсе да

2023-11-20 18:34 UTC, Frilock commented on pom.xml
> +            <version>1.7.0</version>
Вообще такое гуглится.

<properties>
        <!-- настройки проекта -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <jdk.version>1.7</jdk.version>

        <!-- каталог сборки конечного дистрибутива -->
        <distrib.directory>${project.basedir}/distrib</distrib.directory>

        <!-- версии используемых библиотек -->
        <commons-lang3.version>3.4</commons-lang3.version>

        <!-- версии используемых плагинов -->
        <plugin.jar.version>2.6</plugin.jar.version>
        <plugin.dependency.version>2.10</plugin.dependency.version>
        <plugin.resources.version>2.7</plugin.resources.version>
        <plugin.compiler.version>3.1</plugin.compiler.version>
        <plugin.exec.version>1.4.0</plugin.exec.version>
    </properties>

    <dependencies>
        <!-- Здесь добавляете ваши зависимости, например -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang3.version}</version>
        </dependency>

2023-11-20 18:34 UTC, Frilock requested changes
Ответил на ваши комментарии

2023-11-21 08:49 UTC, vladrassvet commented on pom.xml
> +            <version>1.7.0</version>
Спасибо за пример, Иван. Пытался гуглить, но видимо не то. Выполнено.

2023-11-21 08:53 UTC, vladrassvet commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +    private final UserDbStorage userDbStorage;
Выполнено

2023-11-21 12:51 UTC, merged